### ISSUE TITLE
Add support for the puppet version 3.x

### ISSUE THREAD

**Issue by phu-mai** [bibigon812/bibigon812-quagga#12]
Hi  Mr @bibigon812 
    May I know which quagga version should I use for puppet version puppet-3.8.7 please
Thanks so much

**Comment by bibigon812** [comment]
Hi @phu-mai, this module needs puppet >= 4.0

**Comment by phu-mai** [comment]
Hi @bibigon812 how about another release does it support puppet version < 4.0

**Comment by bibigon812** [comment]
Hi @phu-mai. It's the great idea I'll think about it. If you know how to do this tell me how I can implement it. Thank you.

**Comment by phu-mai** [comment]
I think I will choose the way to update P4 on my system that is the best way for now
Thanks so much @bibigon812
