### ISSUE TITLE
Support for access lists

### ISSUE THREAD

**Issue by clxnetom** [bibigon812/bibigon812-quagga#28]
I cannot find any way to create and remove access lists using this modul. Is this something that is in the pipes?

```
access-list 1 remark IP Standard access list
access-list 1 permit host 127.0.0.1
access-list 1 deny any
access-list 100 remark IP extended access list
access-list 100 permit 192.168.0.0 0.0.0.255 any
access-list 100 deny any any
```
I am working on adding it locally but it is an ugly hack ...

PS. Thanks for the static routes and passive interfaces in OSPF, great job!

**Comment by bibigon812** [comment]
@clxnetom , I'll add access-lists this week.

**Comment by clxnetom** [comment]
Fantastic!

Then I will direct my attention elsewhere and check back from time to time. I found it really hard to manage the individual rules in the access-lists in a good way. Had to revert to a `no access-lists ...`  when creating (and I never got `exists?` to work). Here is what I've done if it can be of any use: https://github.com/clxnetom/bibigon812-quagga/tree/access-lists

**Comment by bibigon812** [comment]
@clxnetom 
`access-list 1 permit host 127.0.0.1` == `access-list 1 permit 127.0.0.1`

**Comment by bibigon812** [comment]
@clxnetom you can fetch my last commit and test it. I'll merge to master later.

**Comment by clxnetom** [comment]
Works like a charm for me! Two thumbs up!
