### ISSUE TITLE
FRR-Quagga isn't starting up any daemon

### ISSUE THREAD

**Issue by davirtavares** [bibigon812/bibigon812-quagga#40]
```puppet
node mynode {             
  class { 'quagga':            
    service_file => '/etc/sysconfig/frr',
  }
}
```

This is what I am getting:

root@mynode:~$ service frr status
● frr.service - FRRouting
   Loaded: loaded (/lib/systemd/system/frr.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2018-12-10 21:56:25 EST; 11h ago

Dec 10 21:56:25 mynode frr[23539]: Starting Frr daemons (prio:10):.
Dec 10 21:56:25 mynode frr[23539]: Exiting: failed to connect to any daemons.
Dec 10 21:56:25 mynode frr[23539]: Exiting from the script
Dec 10 21:56:25 mynode frr[23555]: Stopping Frr monitor daemon: (watchfrr).
Dec 10 21:56:25 mynode frr[23555]: Stopping Frr daemons (prio:0): (zebra) (bgpd) (ripd) (ripngd) (ospfd) (ospf6d)
Dec 10 21:56:25 mynode frr[23555]: Stopping other frr daemons..
Dec 10 21:56:25 mynode frr[23555]: Removing remaining .vty files.
Dec 10 21:56:25 mynode frr[23555]: Removing all routes made by FRR.
Dec 10 21:56:25 mynode frr[23555]: Exiting from the script
Dec 10 21:56:25 mynode systemd[1]: Started FRRouting.

It seems like no daemon is being enabled. I can't find in the code any statement that updates /etc/frr/daemons. Am I meant to do that or there's something wrong with the module (or my code above)?

**Comment by bibigon812** [comment]
Hi @davirtavares I think you should change the defaults:

``` yaml
quagga::default_owner: "quagga"
quagga::default_group: "quagga"
quagga::config_dir: "/etc/quagga"
quagga::packages:
  quagga:
    ensure: "present"
```

**Comment by davirtavares** [comment]
Hey @bibigon812, I already did that. Those are my defaults:

```yaml
quagga::default_owner: "frr"   
quagga::default_group: "frr"   
quagga::default_mode: "0600"   
quagga::default_content: "hostname %{::facts.networking.fqdn}\n"
quagga::config_dir: "/etc/frr" 
quagga::service_file_manage: true
quagga::packages:              
  frr:
    ensure: "present"          
````

But the error still occurs. Actually, I have those values set since the beginning.
